### ISSUE TITLE
import from "@brightside/imperative";

### ISSUE THREAD

**Issue by cycaoecw** [zowe/zowe-cli-sample-plugin#30]
Hi, i got error when issue `npm run build` after follow the [Extending a plug-in](https://zowe.github.io/docs-site/latest/extend/extend-cli/cli-extending-a-plugin.html#overview). 

It said can not find @brightside/imperative in package.json. In this case i check the package.json and found that the imperative is using ZOWE. So it updated to `import { RestClient, AbstractSession, ImperativeExpect, Logger } from "@zowe/imperative";` and it is work.

**Comment by tucker01** [comment]
Sorry for the confusion. We're in a transition state for the package scopes. I'll bring this to the team to see what needs updated in our sample and documentation.

**Comment by zFernand0** [comment]
`master` has been stabilized to `@zowe` scoped packages.

`lts-incremental` will remain with `@brightside` references.

Again, apologies for the confusion as we were transitioning everything to be zowe-scoped.
