### ISSUE TITLE
Relicense Repository - EPL+Apache

### ISSUE THREAD

**Issue by MarkAckert** [zowe/zowe-cli-sample-plugin#44]
As this repository contains sample source code intended to be downloaded and expanded upon, it would be better suited with an EPL+Apache 2.0 dual license. 

The OMP Governing Board has approved EPL-2.0 license waivers for sample repositories in Zowe, replaced by the dual license.

To re-license this repository, all contributors should consent by responding to this issue in the affirmative.

**Comment by MarkAckert** [comment]
Plus @ChrisBoehmCA @matthewpwilson , as you are both contributors to this repository please respond to the relicense request!

**Comment by ChrisBoehmCA** [comment]
Good with me.

**Comment by dkelosky** [comment]
affirmative

**Comment by gejohnston** [comment]
I agree.

**Comment by matthewpwilson** [comment]
I agree.

**Comment by JamesBauman** [comment]
I consent

**Comment by MikeBauerCA** [comment]
@MarkAckert or @zFernand0 could you please adjust this license? It looks like we agreed to do it and then it fell off our radar.
