### ISSUE TITLE
Add life-cycle hooks to the sample plug-in

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli-sample-plugin#84]
As a plugin developer I want the sample plugin to demonstrate the appropriate set of functionality to help me implement a valid plugin

Initially introduced in: 
- https://github.com/zowe/imperative/pull/937

**Comment by adam-wolfe** [comment]
Implemented in PR: https://github.com/zowe/zowe-cli-sample-plugin/pull/87
